// <auto-generated />
using CadastroAve.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CadastroAve.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20221111172601_Inicial-criação-CRUD")]
    partial class InicialcriaçãoCRUD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CadastroAve.Models.Ave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Classe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Classe");

                    b.Property<string>("DistribuicaoGeografica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DistribuicaoGeografica");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Especie");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Familia");

                    b.Property<string>("Filo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Filo");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Genero");

                    b.Property<string>("NomeCientifico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeCientifico");

                    b.Property<string>("NomeComum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NomeComum");

                    b.Property<string>("Ordem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Ordem");

                    b.Property<string>("Reino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Reino");

                    b.HasKey("Id");

                    b.ToTable("Ave");
                });
#pragma warning restore 612, 618
        }
    }
}
